apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
  - name: jellyfin-service
    protocol: TCP
    port: 8096
    targetPort: 8096
  type: NodePort
