---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust the storage size as needed
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:10.8.13
        ports:
        - containerPort: 8096
        volumeMounts:
          - name: jellyfin-media
            mountPath: /media
          - name: jellyfin-config
            mountPath: /config
      volumes:
        - name: jellyfin-media
          persistentVolumeClaim:
            claimName: jellyfin-media
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config

